# Generated by Django 3.2.8 on 2021-11-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
