# Generated by Django 3.2.8 on 2021-11-02 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_image_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploadTimeStamp',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
