# Generated by Django 3.2.8 on 2021-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_image_uploadtimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='isHighlight',
            field=models.BooleanField(default=False),
        ),
    ]
